config/routes.rb
AnalisEstruc::Application.routes.draw do
 
  root :to => "home#index"

  get "variables/create"
  get "variables/destroy"

  resources :proyectos do
     resources :variables
  end

  

end

app/models/proyecto.rb
class Proyecto < ActiveRecord::Base
  attr_accessible :nombre_proyecto, :num_var
end

app/models/variable.rb
class Variable < ActiveRecord::Base
  belongs_to :proyecto
  attr_accessible :etiqueta, :proyecto_id, :significado
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
end

app/controllers/proyectos_controller.rb
class ProyectosController < ApplicationController
  # GET /proyectos
  # GET /proyectos.json
  def index
    @proyectos = Proyecto.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @proyectos }
    end
  end

  # GET /proyectos/1
  # GET /proyectos/1.json
  def show
    @proyecto = Proyecto.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @proyecto }
    end
  end

  # GET /proyectos/new
  # GET /proyectos/new.json
  def new
    @proyecto = Proyecto.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @proyecto }
    end
  end

  # GET /proyectos/1/edit
  def edit
    @proyecto = Proyecto.find(params[:id])
    @matriz = {}
  end

  # POST /proyectos
  # POST /proyectos.json
  def create
    @proyecto = Proyecto.new(params[:proyecto])

    respond_to do |format|
      if @proyecto.save
        format.html { redirect_to @proyecto, notice: 'Proyecto was successfully created.' }
        format.json { render json: @proyecto, status: :created, location: @proyecto }
      else
        format.html { render action: "new" }
        format.json { render json: @proyecto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /proyectos/1
  # PUT /proyectos/1.json
  def update
    @proyecto = Proyecto.find(params[:id])

    respond_to do |format|
      if @proyecto.update_attributes(params[:proyecto])
        format.html { redirect_to @proyecto, notice: 'Proyecto was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @proyecto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /proyectos/1
  # DELETE /proyectos/1.json
  def destroy
    @proyecto = Proyecto.find(params[:id])
    @proyecto.destroy

    respond_to do |format|
      format.html { redirect_to proyectos_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/variable_controller.rb
class VariablesController < ApplicationController
  def create
    @proyecto = Proyecto.find(params[:proyecto_id])
    @variable = @proyecto.variables.build(params[:variable])
    @variable.save

    redirect_to @proyecto
  end

  def destroy
  end
end

app/controllers/variables_controller.rb
class VariablesController < ApplicationController
  def create
    @proyecto = Proyecto.find(params[:proyecto_id])
    @variable = @proyecto.variables.build(params[:variable])
    @variable.save
    redirect_to @proyecto
  end

  def destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/proyectos_helper.rb
module ProyectosHelper
end

app/helpers/variable_helper.rb
module VariableHelper
end

app/views/home/index.html.erb
<div style="float: left">
<H4>PROYECTO MIC MAC</h4>
<p> El análisis estructural es una herramienta de estructuración de una reflexión colectiva.<br/> 
Ofrece la posibilidad de describir un sistema con ayuda de una matriz que relaciona todos <br/>
sus elementos constitutivos </p>
<br/>
<p>
  El analisis estructural se realiza por un grupo de trabajo compuesto por actores y expertos<br/>
con experiencia demostrada, pero ello no excluye la intervención de "consejeros" externos.
</p>
<ol>

  <li>P1. Solicitar el numero de variables de nuestro problema.</li>
  <li>P2. Construir un vector V1 que contendra las variables insertadas.</li>
  <li>P3. Anadir relaciones entre las varibales,de forma que se construya una matriz de influecias directas MID.</li>
  <li>P4. Elevar la matriz MID a un potencia k obteniendo como resultado la matriz de posibles influencias 
          <br/>indirectas MPII.</li>
</ol>
<br/>
<p><strong> Nota: </strong>  No se permite que una variable este relacionada consigo misma. (Diagonal principal ceros)</p>

</div>
<div style="float: center; color:blue;">
<h4>Hay cuatro relaciones </h4>
<ul>
<li>    0  no hay relacion </li>
<li>    1  Relacion Debil  </li>
<li>    2  Relacion Moderada </li>
<li>    3  Relacion fuerte.  </li>
<li>    De esta forma si en la posicion de la matriz MID (1,2) <br/>
        hay un 3 quiere decir que la variable 1 posee <br/>
        una relacion fuerte con la variable 2. </li>
</ul>

<h4> -- Mic Mac -- </h4>
 <%= form_for :index do |f| %>
   <div class='field'>
      <% f.text_box, :numvar %>
   </div>
<%end %>
</div>

app/views/layouts/_foot.html.erb
<footer>
   <strong> --- Universidad de La Laguna --- </strong> <br/>
   <p><strong> Especialidad  <%= @itinerario %> 
</footer>

app/views/layouts/_header.html.erb
<div id="header"> &nbsp; </div>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to "HOME", root_path, :class => 'brand' %>
<%= link_to "MIC MAC", 'amm/home', :class => 'brand' %>
<%= link_to "MY TEST", 'amm/test', :class => 'brand' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Prospectiva: Mic Mac" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Prospectiva" %>">

    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body class="<%= controller_name %> <%= action_name %>">
    <header class="navbar navbar-fixed-top">
      <div class="container">
	<%= render 'layouts/header' %>
      </div> 
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </header>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer>
            <div class="field">
               <%= render 'layouts/foot' %>  
             </div>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/proyectos/_form.html.erb
<%= form_for(@proyecto) do |f| %>
  <% if @proyecto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@proyecto.errors.count, "error") %> prohibited this proyecto from being saved:</h2>

      <ul>
      <% @proyecto.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre_proyecto %><br />
    <%= f.text_field :nombre_proyecto %>
  </div>
  <div class="field">
    <%= f.label :num_var %><br />
    <%= f.text_field :num_var %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/proyectos/edit.html.erb
<h1>Fase 2: Descripción de relaciones entre las variables</h1>

<% @proyecto.variables.each do |vars| %>
  <h4> <%= vars.etiqueta %> </h4> 
  <p>  <%= vars.significado %> </p>
<%end%>

<%= link_to 'Mostrar', @proyecto %> |
<%= link_to 'Inicio', proyectos_path %>

app/views/proyectos/index.html.erb
<h1>Listing proyectos</h1>

<table>
  <tr>
    <th>Nombre proyecto</th>
    <th>Num var</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @proyectos.each do |proyecto| %>
  <tr>
    <td><%= proyecto.nombre_proyecto %></td>
    <td><%= proyecto.num_var %></td>
    <td><%= link_to 'Show', proyecto %></td>
    <td><%= link_to 'Edit', edit_proyecto_path(proyecto) %></td>
    <td><%= link_to 'Destroy', proyecto, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Proyecto', new_proyecto_path %>

app/views/proyectos/new.html.erb
<h1>New proyecto</h1>

<%= render 'form' %>

<%= link_to 'Back', proyectos_path %>

app/views/proyectos/show.html.erb
<h1>Proyecto: <%= @proyecto.name %></h1>

<h2> Fase 1: Listado de Variables </h2>

<% @proyecto.variables.each do |vars| %>
  <h4> <%= vars.etiqueta %> </h4> 
  <p>  <%= vars.significado %> </p>
<%end%>

<%= form_for [@proyecto, @proyecto.variables.build] do |f| %>
  <p>Etiqueta    <%= f.text_field :etiqueta%> 
     Significado <%= f.text_field :significado %>
                 <%= f.submit "Guardar" %>
                 <%= link_to 'Ejecutar', proyectos_path %>
 </p>
<%end%>



<%= link_to 'Inicio', proyectos_path %>

app/views/variable/create.html.erb
<h1>Variable#create</h1>
<p>Find me in app/views/variable/create.html.erb</p>

app/views/variable/destroy.html.erb
<h1>Variable#destroy</h1>
<p>Find me in app/views/variable/destroy.html.erb</p>